[workspace]
resolver = "2"
members = [
  "crates/rkyv-js-codegen",
  "crates/rkyv-js-derive",
  "crates/example",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/cometkim/rkyv-js"
