[workspace]
resolver = "2"
members = [
  "rkyv-js-codegen",
  "rkyv-example",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/cometkim/rkyv-js"
